
baseURL = "https://ivanovyordan.github.io/data-engineering-portfolio/"
canonifyURLs = true
relativeURLs = false

languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"


[[menu.main]]
identifier = "about"
name = "About"
url = "about/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "My Work"
url = "projects/"
weight = 2
